addSbtPlugin("org.scala-js"              % "sbt-scalajs"         % "0.6.22")
addSbtPlugin("org.xerial.sbt"            % "sbt-pack"            % "0.9.3")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalajs-bundler" % "0.13.1")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.4")
